### ISSUE TITLE
Strange grouping stage error

### ISSUE THREAD

**Issue by Iranb** [LiuJMzzZ/OpenNCD#2]
When training on cifar10 dataset, the group error like the below:
```
*****Epoch 5 Grouping stage*****
Traceback (most recent call last):
  File "/home/iranb/code/OpenNCD/main.py", line 334, in <module>
    main()
  File "/home/iranb/code/OpenNCD/main.py", line 314, in main
    model.proto_mask = torch.tensor(proto_mask).to(device)
RuntimeError: Could not infer dtype of NoneType
```
How to fix this bug?

**Comment by LiuJMzzZ** [comment]
Sorry and thank you for providing the bug. It occurs when the number of classes is known since few codes are missed in this case. We have fixed it in **main.py** and it should work fine now. Please kindly run the new codes.
